### ISSUE TITLE
Page dedicated to headstage voltage

### ISSUE THREAD

**Issue by jonnew** [open-ephys/onix-docs#11]
There should be a full page dedicated to tethered headstage voltages, what valid ranges are, and why its important. The thin tethers incur significant voltage drops that depend on their length and its the biggest point of confusion for new users that I have encountered so far.

**Comment by ahleighton** [comment]
page added: https://open-ephys.github.io/onix-docs/Hardware%20Guide/Headstages/tether-voltage.html

**Comment by jonnew** [comment]
Just to document the issue, this is a screenshot of what I see when I'm looking at that page 
![image](https://user-images.githubusercontent.com/1429475/164537450-dc0ddb0a-4081-4dea-abc1-ac01524c597d.png)
