### ISSUE TITLE
Weird line spacing in different areas

### ISSUE THREAD

**Issue by jonnew** [open-ephys/onix-docs#2]
Im seeing a lot of inconsistencies in line spacing in bullets, paragraphs etc. Can we just go back to the orginal pydata template in this domain?

![2020-08-13_1135x411_scrot](https://user-images.githubusercontent.com/1429475/90135050-1056f080-dd40-11ea-9936-8cfa37825273.png)

**Comment by jonnew** [comment]
FYI @jsiegle I think found/fixed some errors in the theme_overrides.css that were suppressing a lot of the proper formatting, especially for code documentation. You may want to pull these into your main template.

**Comment by jsiegle** [comment]
Cool, just added them in.
