### ISSUE TITLE
Outdated link on Bonsai.Onix deprecation alert box

### ISSUE THREAD

**Issue by banchan86** [open-ephys/onix-docs#77]
On all the articles under the Bonsai.Onix section, there is a deprecation alert and a redirect link to the new Onix1 package, but it points to https://cjsha.github.io/onix-bonsai-docs/ instead of https://open-ephys.github.io/bonsai-onix1-docs/.

**Comment by cjsha** [comment]
thanks banchan. closed by merging #78
